/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard/route'
import { Route as IndexImport } from './routes/index'
import { Route as DashboardProfileImport } from './routes/dashboard/profile'
import { Route as AuthSignupImport } from './routes/_auth/signup'
import { Route as AuthLoginImport } from './routes/_auth/login'
import { Route as DashboardRoomsIndexImport } from './routes/dashboard/rooms/index'
import { Route as DashboardBookingsIndexImport } from './routes/dashboard/bookings/index'
import { Route as DashboardBookingRequestsIndexImport } from './routes/dashboard/booking-requests/index'
import { Route as DashboardRoomsRoomIdImport } from './routes/dashboard/rooms/$roomId'
import { Route as DashboardBookingsBookingIdViewImport } from './routes/dashboard/bookings/$bookingId.view'
import { Route as DashboardBookingRequestsBookingIdReviewImport } from './routes/dashboard/booking-requests/$bookingId.review'

// Create/Update Routes

const DashboardRouteRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardProfileRoute = DashboardProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const AuthSignupRoute = AuthSignupImport.update({
  id: '/_auth/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRoomsIndexRoute = DashboardRoomsIndexImport.update({
  id: '/rooms/',
  path: '/rooms/',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const DashboardBookingsIndexRoute = DashboardBookingsIndexImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const DashboardBookingRequestsIndexRoute =
  DashboardBookingRequestsIndexImport.update({
    id: '/booking-requests/',
    path: '/booking-requests/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

const DashboardRoomsRoomIdRoute = DashboardRoomsRoomIdImport.update({
  id: '/rooms/$roomId',
  path: '/rooms/$roomId',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const DashboardBookingsBookingIdViewRoute =
  DashboardBookingsBookingIdViewImport.update({
    id: '/bookings/$bookingId/view',
    path: '/bookings/$bookingId/view',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

const DashboardBookingRequestsBookingIdReviewRoute =
  DashboardBookingRequestsBookingIdReviewImport.update({
    id: '/booking-requests/$bookingId/review',
    path: '/booking-requests/$bookingId/review',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof rootRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/rooms/$roomId': {
      id: '/dashboard/rooms/$roomId'
      path: '/rooms/$roomId'
      fullPath: '/dashboard/rooms/$roomId'
      preLoaderRoute: typeof DashboardRoomsRoomIdImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/booking-requests/': {
      id: '/dashboard/booking-requests/'
      path: '/booking-requests'
      fullPath: '/dashboard/booking-requests'
      preLoaderRoute: typeof DashboardBookingRequestsIndexImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/bookings/': {
      id: '/dashboard/bookings/'
      path: '/bookings'
      fullPath: '/dashboard/bookings'
      preLoaderRoute: typeof DashboardBookingsIndexImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/rooms/': {
      id: '/dashboard/rooms/'
      path: '/rooms'
      fullPath: '/dashboard/rooms'
      preLoaderRoute: typeof DashboardRoomsIndexImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/booking-requests/$bookingId/review': {
      id: '/dashboard/booking-requests/$bookingId/review'
      path: '/booking-requests/$bookingId/review'
      fullPath: '/dashboard/booking-requests/$bookingId/review'
      preLoaderRoute: typeof DashboardBookingRequestsBookingIdReviewImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/bookings/$bookingId/view': {
      id: '/dashboard/bookings/$bookingId/view'
      path: '/bookings/$bookingId/view'
      fullPath: '/dashboard/bookings/$bookingId/view'
      preLoaderRoute: typeof DashboardBookingsBookingIdViewImport
      parentRoute: typeof DashboardRouteImport
    }
  }
}

// Create and export the route tree

interface DashboardRouteRouteChildren {
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardRoomsRoomIdRoute: typeof DashboardRoomsRoomIdRoute
  DashboardBookingRequestsIndexRoute: typeof DashboardBookingRequestsIndexRoute
  DashboardBookingsIndexRoute: typeof DashboardBookingsIndexRoute
  DashboardRoomsIndexRoute: typeof DashboardRoomsIndexRoute
  DashboardBookingRequestsBookingIdReviewRoute: typeof DashboardBookingRequestsBookingIdReviewRoute
  DashboardBookingsBookingIdViewRoute: typeof DashboardBookingsBookingIdViewRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardRoomsRoomIdRoute: DashboardRoomsRoomIdRoute,
  DashboardBookingRequestsIndexRoute: DashboardBookingRequestsIndexRoute,
  DashboardBookingsIndexRoute: DashboardBookingsIndexRoute,
  DashboardRoomsIndexRoute: DashboardRoomsIndexRoute,
  DashboardBookingRequestsBookingIdReviewRoute:
    DashboardBookingRequestsBookingIdReviewRoute,
  DashboardBookingsBookingIdViewRoute: DashboardBookingsBookingIdViewRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/rooms/$roomId': typeof DashboardRoomsRoomIdRoute
  '/dashboard/booking-requests': typeof DashboardBookingRequestsIndexRoute
  '/dashboard/bookings': typeof DashboardBookingsIndexRoute
  '/dashboard/rooms': typeof DashboardRoomsIndexRoute
  '/dashboard/booking-requests/$bookingId/review': typeof DashboardBookingRequestsBookingIdReviewRoute
  '/dashboard/bookings/$bookingId/view': typeof DashboardBookingsBookingIdViewRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/rooms/$roomId': typeof DashboardRoomsRoomIdRoute
  '/dashboard/booking-requests': typeof DashboardBookingRequestsIndexRoute
  '/dashboard/bookings': typeof DashboardBookingsIndexRoute
  '/dashboard/rooms': typeof DashboardRoomsIndexRoute
  '/dashboard/booking-requests/$bookingId/review': typeof DashboardBookingRequestsBookingIdReviewRoute
  '/dashboard/bookings/$bookingId/view': typeof DashboardBookingsBookingIdViewRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/rooms/$roomId': typeof DashboardRoomsRoomIdRoute
  '/dashboard/booking-requests/': typeof DashboardBookingRequestsIndexRoute
  '/dashboard/bookings/': typeof DashboardBookingsIndexRoute
  '/dashboard/rooms/': typeof DashboardRoomsIndexRoute
  '/dashboard/booking-requests/$bookingId/review': typeof DashboardBookingRequestsBookingIdReviewRoute
  '/dashboard/bookings/$bookingId/view': typeof DashboardBookingsBookingIdViewRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/dashboard/profile'
    | '/dashboard/rooms/$roomId'
    | '/dashboard/booking-requests'
    | '/dashboard/bookings'
    | '/dashboard/rooms'
    | '/dashboard/booking-requests/$bookingId/review'
    | '/dashboard/bookings/$bookingId/view'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/dashboard/profile'
    | '/dashboard/rooms/$roomId'
    | '/dashboard/booking-requests'
    | '/dashboard/bookings'
    | '/dashboard/rooms'
    | '/dashboard/booking-requests/$bookingId/review'
    | '/dashboard/bookings/$bookingId/view'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/_auth/login'
    | '/_auth/signup'
    | '/dashboard/profile'
    | '/dashboard/rooms/$roomId'
    | '/dashboard/booking-requests/'
    | '/dashboard/bookings/'
    | '/dashboard/rooms/'
    | '/dashboard/booking-requests/$bookingId/review'
    | '/dashboard/bookings/$bookingId/view'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/dashboard",
        "/_auth/login",
        "/_auth/signup"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard/route.tsx",
      "children": [
        "/dashboard/profile",
        "/dashboard/rooms/$roomId",
        "/dashboard/booking-requests/",
        "/dashboard/bookings/",
        "/dashboard/rooms/",
        "/dashboard/booking-requests/$bookingId/review",
        "/dashboard/bookings/$bookingId/view"
      ]
    },
    "/_auth/login": {
      "filePath": "_auth/login.tsx"
    },
    "/_auth/signup": {
      "filePath": "_auth/signup.tsx"
    },
    "/dashboard/profile": {
      "filePath": "dashboard/profile.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/rooms/$roomId": {
      "filePath": "dashboard/rooms/$roomId.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/booking-requests/": {
      "filePath": "dashboard/booking-requests/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/bookings/": {
      "filePath": "dashboard/bookings/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/rooms/": {
      "filePath": "dashboard/rooms/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/booking-requests/$bookingId/review": {
      "filePath": "dashboard/booking-requests/$bookingId.review.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/bookings/$bookingId/view": {
      "filePath": "dashboard/bookings/$bookingId.view.tsx",
      "parent": "/dashboard"
    }
  }
}
ROUTE_MANIFEST_END */
